### DISCUSSION TITLE
How to create autonumbering or auto-incrementing fields?

### DISCUSSION THREAD

**Discussion by cueckoo** [cue-lang/cue#1002] [Q&A]
_Originally opened by @jugaadi in https://github.com/cuelang/cue/discussions/1002_

Expected output(yaml):

```yaml
res1:
# Each resource needs to be given a unique identifier. Ex. An auto-incrementing number within the scope of the doc
    x-rid: 1 
    type: object
    properties:
        prop1: 
# Each property needs to be given a unique identifier. Ex. An auto-incrementing number wiithin the scope of the resource(parent)
            x-pid: 1
            type: string
        prop2: 
            x-pid: 2
            type: string
        prop3: 
            x-pid: 3
            type: boolean
res2:
    x-rid: 2
    type: object
    properties:
        prop1: 
            x-pid: 1
            type: number
        prop2: 
            x-pid: 2
            type: boolean
```
