### DISCUSSION TITLE
Using Cue to replace depends_on in YAML.

### DISCUSSION THREAD

**Discussion by jer-k** [cue-lang/cue#1211] [General]
I'm trying to wrap my head around how I can use Cue to replace a YAML structure that has `depends_on`, such as `docker-compose.yml`. 

Something simple might be a Rails API that depends on a Postgres database. Here is an example compose file I have.

```
version: '3'
services:
  api:
    build: .
    image: rails_postgres_redis:latest
    command: bash -c "(rake db:exists && rake db:migrate || rake db:setup) && bundle exec rails s -b 0.0.0.0"
    environment:
      REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: postgres:12-alpine
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
```

When you `docker-compose up`, compose will spin up `db` first and then `api` second. I want to translate this sort of behavior to Cue. My very rough sketch for this where I'm only focusing on the name of the service and the depends on looks something like

```
#ErrorMessage: {
  message: "Something went wrong"
}

#Service: {
  name: string,
  success: bool
}

#Compose: {
  services: [...#Service | #ErrorMessage]
}

api: #Service & {
  name: "api"
}

db: #Service & {
  name: "db"
}

myCompose:  #Compose & {
  services: [
    db,
    if (db.success) {
      api
    }
    if (!db.success) {
      #ErrorService
    }
  ]
}
```

Now the part I'm running into a mental block with how to get the full output from `myCompose`. `cue eval -c` fails because there is incomplete data, `db.success` is has not been defined. In this contrived example I could input that value, but in a more complex branching structure where there are many levels of depends on, I'm struggling to understand how I could paint a full picture of all the possibilities.

Imagine wanting to generate a graph showing the different paths / outcomes to a user based on the definition of their Cue file or translating the `services` into database objects with proper relations on what to run next if something is successful.
