### DISCUSSION TITLE
Importing Kubernetes objects, both namespaced and global

### DISCUSSION THREAD

**Discussion by mxey** [cue-lang/cue#1260] [Q&A] [answered]
I am trying to use `cue import` to import Kubernetes YAML files. Some of the objects are namespaced, some are not.

Given this `example.yaml`:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
rules:
  # Allow Metrics Scraper to get metrics from the Metrics server
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-dashboard
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: kubernetes-dashboard
```

This CUE command will not work:

```
cue import -p kubecluster -l '"objects"' -l '"namespaced"' -l metadata.namespace -l kind -l metadata.name  -f example.yaml 
```

with this error:
```
error evaluating label metadata.namespace: undefined field: namespace
```

I would like to import the namespaced objects as `objects.namespaced.NS.KIND.NAME` and the non-namespaced objects as `objects.global.KIND.NAME`. I know that in the past the path flag for `cue import` worked differently, but I don't see how a different path structure would be possible with the path flag as it is today? 

I would be fine with a placeholder namespace for global objects which I could then remove with a string replace. But this also fails:

```
cue import -p kubecluster -l '"objects"' -l '"namespaced"' -l '(*metadata.namespace | "")' -l kind -l metadata.name  -f example.yaml
```

```
panic: interface conversion: *ast.BinaryExpr is not ast.Label: missing method labelNode [recovered]
        panic: interface conversion: *ast.BinaryExpr is not ast.Label: missing method labelNode

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0000afec0)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0x1824b80, 0xc000292630)
        /opt/hostedtoolcache/go/1.15.12/x64/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/cmd/cue/cmd.placeOrphans(0xc00031da00, 0xc0000eeab0, 0x7ffeefbff816, 0xb, 0xc0001c6d40, 0x2, 0x2, 0x2, 0x0, 0x8)
        /home/runner/work/cue/cue/cmd/cue/cmd/orphans.go:211 +0x11db
cuelang.org/go/cmd/cue/cmd.(*buildPlan).placeOrphans(0xc00031da00, 0xc00000a1e0, 0xc0000981f8, 0x1, 0x1, 0x1, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/orphans.go:140 +0x7bf
cuelang.org/go/cmd/cue/cmd.parseArgs(0xc000324220, 0xc000248c40, 0x1, 0xe, 0xc000326870, 0xc00031da00, 0x0, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/common.go:650 +0xbdb
cuelang.org/go/cmd/cue/cmd.runImport(0xc000324220, 0xc000248c40, 0x1, 0xe, 0x11fce60, 0xc0002a1c88)
        /home/runner/work/cue/cue/cmd/cue/cmd/import.go:314 +0x24e
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000338dc0, 0xc000248c40, 0x1, 0xe, 0x0, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000338dc0, 0xc000248b60, 0xe, 0xe, 0xc000338dc0, 0xc000248b60)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000241080, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000324220, 0x19f5b00, 0xc000036090, 0x0, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0x19f5b00, 0xc000036090, 0xc000030110, 0xf, 0xf, 0x192fd70, 0xc0002a1f48)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc000078058)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
        /home/runner/work/cue/cue/cmd/cue/main.go:24 +0x25
```
