### DISCUSSION TITLE
Cue generate Yaml Configs

### DISCUSSION THREAD

**Discussion by zombiebober** [cue-lang/cue#1266] [Q&A] [answered]
In our project, we use go template to generate yaml configs.

An example of our yaml template:
```
auth:
  addr:  &usersvc {{var "auth-server" "host"}}:{{global "auth-server" "grpc-port"}}
  tls:
    disable: {{global "tls" "disable"}}
    ServerName: {{global "tls" "server-name"}}
    TrustedCA: {{global "tls" "ca"}}
    Cert: {{global "tls" "client" "cert"}}


grpc:
  addr: :{{- global "server" "grpc-port"}}
  tls:
    disable: {{global "tls" "disable"}}
    ServerName: {{global "tls" "server-name"}}
    TrustedCA: {{global "tls" "ca"}}
    Cert: {{global "tls" "server" "cert"}}
    CertKey: {{global "tls" "server" "private-key"}}
  client:
    ClientCert: {{global "tls" "client" "cert"}}
    ClientKey: {{global "tls" "client" "private-key"}}
    
database:
  pg:
    host: {{var "preferences-db" "host"}}
    port: {{var "preferences-db" "port"}}
    db: {{var "preferences-db" "db"}}
    user: {{var "preferences-db" "user"}}
    password: {{var "preferences-db" "password"}}

```

'global' function looks for a value along the path in the global map[string]interface{}
'var' function looks for a value in the block of mode variables, which is specified through the flags of the generator.

Variable values ​​are located in the variable.yaml file:

```
global:
  tls:
    disable: false
    grpc-disable: false
    server-name: "server"
    ca: /var/lib/certs/ca.pem
    server:
        cert: /var/lib/certs/server.pem
        private-key: /var/lib/certs/server-key.pem
    client:
        cert: /var/lib/certs/client.pem
        private-key: /var/lib/certs/client-key.pem
  server:
    http-port: 443
    grpc-port: 3401
  auth-server:
    http-port: 2020
    grpc-port: 2021
    
mode-variables:
  localhost-production:
    preferences-db:
      host: localhost
      port: 5432
      db: prod-preferences
      user: postgres
      password: prod-pass
  localhost-windows:
    preferences-db:
      host: localhost
      port: 5496
      db: windows-preferences
      user: postgres
      password: pass
```

I would like to use cuelang, since the go template is too weak a tool for generating configs.

1. How can cuelang mapping the values ​​of variables?
2. How can pass values ​​to cuelang to generate yaml configs?
3. How to generate dynamic yaml configs using cuelang?

**Comment by verdverm** [comment, marked as answer]
I would use the following patterns, given you want to maintain the variables as Yaml. My personal preference would be to convert all inputs to CUE.

`main.cue`
```cue
// schemas
#Global: {
        host: string
}

#Mode: {
        user: string
}

// yaml vars validation
global: #Global
mode: [env=string]: #Mode

// "flags" for controlling selection
#env: string | *"dev" @tag(env)

// output mapping, uses the current "function" syntax for CUE
#Output: {
       // defines a top level input value, could have them individually
        #IN: {
                global: #Global
                vars: #Mode
        }

        // the result is where the actual mapping happens
        result: {
                login: "\(#IN.vars.user)@\(#IN.global.host)"
        }
}

// "calling" the mapping with concrete inputs
final: (#Output & { #IN:{ "global": global, vars: mode[#env]} }).result
```

`vars.yaml`
```yaml
global:
  host: domain.com

mode:
  dev:
    user: "dev"
  prd:
    user: "prd"
```

`$ cue eval main.cue vars.yaml --out yaml -e final`

```yaml
login: "dev@domain.com"
```

`$ cue eval main.cue vars.yaml --out yaml -e final -t env=prd`

```yaml
login: "prd@domain.com"
```

things to note:

- `cue` will merge CUE and data files by default
- we enforced a schema on the data files by matching the top-level keys
- we used `@tag` to provide dynamic selection of subfields in the input
- we used "function" syntax to make the mapping reusable, where "function" is like `(#Mapping & {...}).result`. This is just a pattern the community has come up with. There is a proposal for simplifying the syntax.

**Reply by zombiebober** [reply]
Thanks! Are there any special options for working with references in YAML?

example:
```
addr:  &usersvc {{var "auth" "host"}}:{{global "auth" "port"}}

monitoring:
  http:
    userservice:
      url: *usersvc
      interval: 10s
```
