### DISCUSSION TITLE
Setting a value of a nested path from for loop in a tool.

### DISCUSSION THREAD

**Discussion by iilyak** [cue-lang/cue#1278] [Q&A]
moving conversation from an issue https://github.com/cue-lang/cue/issues/1276

I have a list of users under `_users` key. Each user is a structure which has a `_ssh_authorized_keys` key. The `_ssh_authorized_keys` is a list. My goal is to develop a cue tool which would inject the `ssh_key` into `_users[name]._ssh_authorized_keys[*]`.

Here is the code structure 
```
command: "gen": {
	for user in _users {
		for _key in user._ssh_authorized_keys if _key.key == "{generate}" {
			"key-\(user.name)": file.Read & {
				filename: "identities/\(user.name).pub"
				contents: string
			}
		}
		// how do I append a new value into `ssh_authorized_keys` for each key for each user
	}
}
```

I am trying to produce the following output to the console.

```
users:
  - name: user1
    ssh-authorized-keys:
      - ssh-ed25519 AAAACuser1......1 user1
      - ssh-ed25519 AAAACuser1......2 user1
  - name: user2
    ssh-authorized-keys:
      - ssh-ed25519 AAAACuser2.....1 user2
      - ssh-ed25519 AAAACuser2......2 user2
  ```

given the:
```
#ssh_key: {
	key: string
	type: "ed25519" | "rsa" | "ecdsa"
}

let generate = #ssh_key & {key: "{generate}", type: "ed25519"}

#user: {
	name: string
	_sudo: bool
	shell: "/bin/bash"
	_ssh_authorized_keys: [generate]
}

_users: [
	#user & {name: "user1", _sudo: true, _ssh_authorized_keys: [generate]},
	#user & {name: "user2", _sudo: true},
	#user & {name: "user3", _sudo: false}
]
```
Questions:
- how to refer to a path to assign values (`_users[user.name]._ssh_authorized_keys: "something"` doesn't work)?
- how to use "key-\(user.name)" in a reference (`"key-\(user.name)".key` doesn't work)?
- how to iterate array and get current index so I can use `_users[idx]` to refer to the user structure?
