### DISCUSSION TITLE
Bug or misunderstanding? And a question.

### DISCUSSION THREAD

**Discussion by trantor** [cue-lang/cue#1512] [Q&A] [answered]
Hello everyone.
I've discovered cue through the FOSDEM talk and basically I immediately started to use it to standardize my yaml ansible inventories with their variables structures. Btw it's magnificent ;D

As it often happens to me I got into a moderately complex requirement pretty soon and started experimenting to find a way to express it properly with cue.
However I stumbled into what appears to be a bug, but given my relative inexperience I decided to ask here first.

I simplified my structure to display the problem in `constraint.cue`

```
#host1 | #host2 | #host3

#host1: #generic_host & {
    type: "type1"
    ...
}

#host2: #generic_host & {
    type: "type2"
    ...
}

#host3: this={
    type: "type3"
    vhosts: [...#vhost]
    #test: this.type
} & #generic_host

#generic_host: {
    type: "type1" | "type2" | "type3"
    proxy_env: close({
        http_proxy?: =~"^http://.+"
        https_proxy?: http_proxy
    })
    ...
}

#vhost: #a_vhost | #b_vhost | #c_vhost

#a_vhost: #generic_vhost & {
    type: "a"
}

#b_vhost: #generic_vhost & {
    type: "b"
}

#c_vhost: #generic_vhost & {
    type: "c"
    sw: string
}

#generic_vhost: {
    name: != ""
    type: "a" | "b" | "c"
    ...
}
```
I created a YAML `example.yaml` file to merge with:
```yaml
type: type3
vhosts:
  - name: name
    type: c
    sw: sw1
proxy_env: {}
```

However I get strange output
```
$ cue export /tmp/example.yaml /tmp/constraint.cue
field not allowed: #test
```

If I change `#host1 | #host2 | #host3` to `host3` at the top I get
```
$ cue export /tmp/example.yaml /tmp/constraint.cue
{
    "type": "type3",
    "vhosts": [
        {
            "name": "name",
            "type": "c",
            "sw": "sw1"
        }
    ],
    "proxy_env": {}
}
```
That's bizarre.
What's even more bizarre is that, after restoring  `#host1 | #host2 | #host3`, if I convert my YAML example into CUE using `cue export`...
```
$ cue export --out=cue /tmp/example.yaml > /tmp/example.cue
$ cue export /tmp/example.cue /tmp/constraint.cue
{
    "type": "type3",
    "vhosts": [
        {
            "name": "name",
            "type": "c",
            "sw": "sw1"
        }
    ],
    "proxy_env": {}
}
```

My original intent was to apply a derivation of what found [here](https://cuetorials.com/patterns/fields/) to express a specific constraint.
Let's say that with a yaml file such as
```yaml
vhosts:
  - name: "vhostA"
    saml_auth: true
  - name: "vhostB"
    saml_auth: false
saml_daemon:       # saml_daemon should be mandatory only if at least one vhost has saml_auth to true
  name: "whatever"
```
I wish to express, with a conditional, that the `saml_daemon` tree should be optional when no vhost has `saml_auth` set to `true`, and be mandatory otherwise.
I am not sure whether there's a workaround to achieve that. Is there a way?

**Comment by eonpatapon** [comment]
I'm not sure what is going on with the `#test` field. Looks like a bug to me.

About the `saml_daemon` check, here's a possibility:

```cue
#vhost: {
	name:      string
	saml_auth: *false | bool
}

#host: {
	vhosts: [...#vhost]
	saml_daemon?: {
		name: string
	}
	// Make the saml_daemon required if some vhost has saml_auth set to true
	for v in vhosts
	if v.saml_auth {
		saml_daemon: _
	}
}

#host
```

```
 cat test.yaml 
vhosts:
  - name: "vhostA"
    saml_auth: true
  - name: "vhostB"
    saml_auth: false
# saml_daemon:
#   name: "whatever"
 cue export schema.cue test.yaml 
saml_daemon.name: incomplete value string
```

**Reply by trantor** [reply]
Thanks @eonpatapon . I've managed to come up with a similar solution, although I wanted a field which would be optional or mandatory depending on the condition, which I almost achieved although not fully so. However the bug I mentioned continues to bite in unexpected moments. The really bizarre part is that it seems to originate only with the yaml file and not with the converted cue file.

**Comment by trantor** [comment]
I've noticed that I used conjunctions in place of embedding in my first example. 
But the problem seems to be even more basic So I created another simple example because I feel something is staring me right in the face

YAML Data
```yaml
type: first
a_list:
  - a
  - b
```

CUE code
```
#first_host | #other_host | #second_host

#first_host: {
    type: "first"
    a_list: [...]
}

#other_host: {
    type: "other"
}

#second_host: {
    type: "second"
}
```

And I get
```
$ cue eval /tmp/basic_sample.yaml basic.cue 
field not allowed: a_list
```
I am definitely missing something here. Again if I cut down the first disjunction to the single matching definition it works fine.

**Reply by eonpatapon** [reply]
It's related to the fact the disjunction is at the top level of the document. If you place it in a field, it works:

```cue
#first_host: {
	type: "first"
	a_list: [...]
}

#other_host: {
	type: "other"
}

#second_host: {
	type: "second"
}

h: #first_host | #other_host | #second_host
```

```yaml
h:
  type: first
  a_list:
    - a
    - b
```

```
 cue export test.cue test.yaml 
{
    "h": {
        "type": "first",
        "a_list": [
            "a",
            "b"
        ]
    }
}
```
