### DISCUSSION TITLE
Inject value and files in the command yaml.MarshalStream

### DISCUSSION THREAD

**Discussion by sgendrot** [cue-lang/cue#1747] [Q&A] [answered]
Hi,

I try to use injection with the command **yaml.MarshalStream**

The context:
I have a **template.cue**:
```
deployments: [Name=_]: {
	apiVersion: "apps/v1"
	kind:       "Deployment"
	metadata: {
		name: Name
		labels: {
			app:       Name
			domain:    string | *"dev"
		}
	}
}
```

and 4 value files, 1 "common" and 3 "env files" (staging, preprod, prod).

I load the **common.cue** file every times:
```
deployments: mydep: {
	metadata: {
		labels: {
			labelX: "common"
			env: string | *"dev"
			}
	}
}
```

I add specific in the env files, like in the **staging.cue**:
```
@if(staging)

deployments: mydep: {
	metadata: {
		labels: {
			env: "staging"
			domain: "staging"
			}
	}
}
```

Then I choose which env files to use with tags:
`cue eval -c *.cue -t staging`

With the command **cue eval**, it's working well and I want to use the injection with the command **yaml.MarshalStream** .
Example:
```
command: gen_yaml: {
	task: print: cli.Print & {
		text: yaml.MarshalStream(objects)
	}
}
```

For the complete overview:
https://github.com/sgendrot/cue-ci
I'm at the [step13](https://github.com/sgendrot/cue-ci/tree/main/step13), it's a mix of [step12 (Generate deployments and Services)](https://github.com/sgendrot/cue-ci/tree/main/step12) and [step7 (Values files per environments) ](https://github.com/sgendrot/cue-ci/tree/main/step7)

I'm stuck and I don't find the solution or an alternative.

Thx for the help

**Comment by myitcv** [comment]
What is `objects` here? A value you are looking to inject? 

Can you give an example of what exactly is not working?

**Reply by sgendrot** [reply]
ok, I don't use the cli properly, I tried `cue gen_yaml -t staging` instead of `cue -t staging gen_yaml`

So in my example, I can switch env file with the injection.

If I use the command `cue gen_yaml`
the result is:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  labels:
    labelX: common
    app: mydep
    env: dev
    domain: dev
```
If I use the command `cue -t staging gen_yaml`
the result is:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  labels:
    labelX: common
    app: mydep
    env: staging
    domain: staging
```

I just have to add a **prod.cue**:
```
@if(prod)

deployments: mydep: {
	metadata: {
		labels: {
			env: "prod"
			domain: "prod"
			}
	}
}

deployments: proddep: metadata:labels: testinject: string | *"default" @tag(val)
```

And I use the command: `cue -t prod -t val=changed gen_yaml`
result:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  labels:
    labelX: common
    app: mydep
    env: prod
    domain: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proddep
  labels:
    testinject: changed
    app: proddep
    domain: dev
```
I can use the injection to manage the differences between env (one or several files by env), and change some variables (like the label _testinject_).
