### DISCUSSION TITLE
"on" and "off"  is output to yaml file as a string

### DISCUSSION THREAD

**Discussion by lll-lll-lll-lll** [cue-lang/cue#1762] [Q&A] [answered]
# Problem
The keywords on and off would be output to yml as strings.
I'd like to know how to fix this.
# ReCreate
command: ```cue eval base.cue  --out yaml ```
base.cue
```base.cue
name: "Base Workflow"

on: {
	workflow_call:

	push: branches: [
		"develop",
	]
}

jobs: build: {
	"runs-on": "ubuntu-latest"
	strategy: matrix: {
		os: ["ubuntu-latest", "macos-latest", "windows-latest"]
		"python-version": ["3.8", "3.9"]
	}

	steps: [{
		uses: "actions/checkout@v3"
	}, {
		name: "setup python ${{ matrix.python-version }}"
		uses: "actions/setup-python@v4"
		with: {
			"python-version": "${{ matrix.python-version }}"
			architecture:     "x64"
		}
	}, {
		name:  "dependencies"
		shell: "bash"
		run: """
			pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
			python -m pip install --upgrade pip
			pip install flake8 pytest
			pip install -r requirements.txt --target=\".python_packages/lib/site-packages\"
			popd

			"""
	}, {
		name: "Test with pytest"
		run:  "pytest"
	}]
}
```

## output
```yml
name: Base Workflow
"on":
  workflow_call: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.8"
          - "3.9"
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: dependencies
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
      - name: Test with pytest
        run: pytest

```
