### DISCUSSION TITLE
Can't figure out how YAML maps work

### DISCUSSION THREAD

**Discussion by skorokithakis** [cue-lang/cue#1777] [General] [answered]
I have this CUE schema:

```cue
#Apps: {
	[string]: #App

	#App: {
		enabled?:          bool
		url:               string
		branch?:           string
		environment_file?: string
		environment?: {string: string}
		replacements?: {string: string}
		compose_config?: [...string] | string
	}
}

apps: #Apps

config: {prune: bool}
```

I'm trying to validate this YAML file:

```yaml
apps:
  bar:
    url: https://example.com/stavros/foo.git
    environment:
      FOO: bar
```

However, I get an error:

```
apps.bar.environment: field not allowed: FOO:
    ./harbormaster.cue:2:12
    ./harbormaster.cue:9:17
    ./harbormaster.cue:15:7
    ./harbormaster.yml:5:8
```

I don't know why, since I have the map defined. What am I doing wrong?
