### DISCUSSION TITLE
Set schema for an unknown field name

### DISCUSSION THREAD

**Discussion by ahmed711** [cue-lang/cue#1901] [Q&A] [answered]
Hi all, 
this might be a problem in the hierarchy of the yaml files we are trying to validate but it might be good to know if this option exists 
we have a yaml file that is constructed as follows 

```
student1:
  address: 
  phone: 
  ...
student2:
  address:
  phone: 
  ...
student3:
  address:
  phone:
  ...

```
I want to validate the data on the file but I am not sure how to match any field
I was thinking something like this 

```
 "\w": {
  address: string
  phone: int
  ...
}
``` 
but I am not sure about the right expression to match any student name or match any field
