### DISCUSSION TITLE
How can I import external file into CUE file?

### DISCUSSION THREAD

**Discussion by uphy** [cue-lang/cue#1996] [Q&A] [answered]
I'm trying to describe k8s manifest in cue language.
I have trouble describing `ConfigMap` ([ref](https://kubernetes.io/docs/concepts/configuration/configmap/)).

K8s's `ConfigMap` can include multiple key-values in yaml file:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
```

I want to define a key-value pair from an external file like golang's `embed` feature.

```shell
$ tree
.
├── config-map.cue
└── game.properties
```

`config-map.cue`

```cue:config-map.cue
package main

#ConfigMap: {
	apiVersion: "v1"
	// ...
	data?: {[string]: string}
}

ConfigMapExample: #ConfigMap & {
	data: {
		"game.properties": string @embed("./game.properties", string)
	}
}
```

`game.properties`

```properties:game.properties
enemy.types=aliens,monsters
player.maximum-lives=5  
```

Is it possible to achieve something similar to that with the cue language?
Or do I need to write an extension in the Go language?
