### DISCUSSION TITLE
For loop list a conflicting values

### DISCUSSION THREAD

**Discussion by gujiwork** [cue-lang/cue#2037] [Q&A] [answered]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cuelang.org/go v0.4.3
</pre>

### What did you do?

```
params: #input
uiSchema: {}
#input: {
	name: string
	appName: string
	appEnv: string
	namespace: *"system" | string
	workspace: params.appName + params.appEnv | string
	triggers: {
		...
	}
	stages: [...{
		name: string
		customParams: {
			...
		}
		jobs: [...{
			id?: int
			created_at: string
			updated_at: string
			name: string
			stepType: string
			params: {
				...
			}
			image: string
		}]
	}]

}
output: {
	apiVersion: "tekton.dev/v1beta1"
	kind:       "Pipeline"
	metadata: {
		name:      params.appName + params.appEnv
		namespace: params.namespace
	}
	spec: {
		workspaces: [{
//			name: "git-credentials"
//			description: "ssh credentials"
			name: "healthtest"
			description: "This workspace contains the cloned repo files, so they can be read by the next task"
		}]
		"params": [
			for stage in params.stages {
				if stage.customParams != _|_ {
				  for key, value in stage.customParams {
						{
							name: key
							default: value
						}
					}
				}
			}
		]
		tasks: [
			{
					name: "fetch-source"
					taskRef:
						name: "git-clone"
					workspaces: [{
						name: "output"
						workspace: "healthtest"
		//      	name: "ssh-directory"
		//      	workspace: "git-credentials"
					}]
					"params": [
					 for stage in params.stages {
							for key, value in stage.customParams {
								{
									name: key
									value: "$(params." + key + ")"
								}
							}
					 }
					]
			},
			for i, stage in params.stages {
			  if i == 0 {
					for job in stage.jobs {
						{
							name: job.name
							runAfter: ["fetch-source"]
							taskRef:
								name: job.name
							workspaces: [{
								name: "output"
								workspace: "healthtest"
		//								name: "ssh-directory"
		//								workspace: "git-credentials"
							}]
							"params": [
								for key, value in stage.customParams {
									{
										name: key
										value: "$(params." + key + ")"
									}
								}]
						},
					}
				}
			  if i > 0 {
					for job in stage.jobs {
						{
							name: job.name
							runAfter: [
									for job in params.stages[i-1].jobs {
										job.name
									}
							]
							taskRef:
								name: job.name
							workspaces: [{
								name: "output"
								workspace: "healthtest"
		//								name: "ssh-directory"
		//								workspace: "git-credentials"
							}]
							"params": [
								for key, value in stage.customParams {
									{
										name: key
										value: "$(params." + key + ")"
									}
								}
							]
					  }
					}
			  }
			}
		]
	}
}

```
json 
```
{
	"stages": [{
		"name": "test-1",
		"customParams": {
			"t": "2"
		},
		"jobs": [{
			"name": "make-code-1",
			"stepType": "execute_shell",
			"params": {
				"scriptType": "bash",
				"scriptContent": "#!/bin/bash \n ls -l /root\n pwd"
			},
			"image": "alpine:latest"
		}, {
			"name": "make",
			"stepType": "execute_shell",
			"params": {
				"scriptType": "bash",
				"scriptContent": "#!/bin/bash \n ls -l /root\n pwd"
			},
			"image": "alpine:latest"
		}]
	}, {
		"name": "test-2",
		"customParams": {
			"t3": "3"
		},
		"jobs": [{
			"name": "upload-oss-1",
			"stepType": "execute_shell",
			"params": {
				"scriptType": "bash",
				"scriptContent": "#!/bin/bash \n ls -l /root\n pwd"
			},
			"image": "alpine:latest"
		}, {
			"name": "upload-oss-2",
			"stepType": "execute_shell",
			"params": {
				"scriptType": "bash",
				"scriptContent": "#!/bin/bash \n ls -l /root\n pwd"
			},
			"image": "alpine:latest"
		}]
	}, {
		"name": "test-3",
		"customParams": {
			"a": "127.0.0.1"
		},
		"jobs": [{
			"name": "deploy",
			"stepType": "execute_shell",
			"params": {
				"scriptType": "bash",
				"scriptContent": "#!/bin/bash \n ls -l /root\n pwd"
			},
			"image": "alpine:latest"
		}]
	}],
	"name": "health-dev-flow",
    "appName": "health",
    "appEnv": "dev",
	"triggers": {
		"gitUrl": "1",
		"gitBranch": "1",
		"secretType": "pass",
		"secret": "jack"
	}
}
```

### What did you expect to see?
```
  tasks:
  - name: show-readme
    runAfter: ["fetch-source"]
    taskRef:
      name: make-code-1
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: t
      value: $(params.t)
    - name: t3
      value: $(params.t3)
    - name: a
      (value: $(params.a))

  - name: make
    runAfter: ["make-code-1"]
    taskRef:
      name: make
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: t
      value: $(params.t)
    - name: t3
      value: $(params.t3)
    - name: a
      (value: $(params.a))
```

### What did you see instead?
```
"err":"output.spec.tasks.1.name: conflicting values \"make\" and \"make-code-1\""}

```

**Comment by slewiskelly** [comment, marked as answer]
I think breaking this down to something more simple would help you and other people trying to help.

So let's go with:

```cue
_stages: [{
    name: "s1"
    jobs: [
        { name: "j1" },
    ]
}, {
    name: "s2"
    jobs: [
        { name: "j2" },
    ]
}, {
    name: "s3"
    jobs: [
        { name: "j3"},
        // { name: "j4" }
    ]
}]
```

And a list populated by a comprehension:

```cue
tasks: [for stage in _stages {
    for job in stage.jobs {
        name: job.name
    }
}]
```

So far so good:

```yaml
tasks:
  - name: j1
  - name: j2
  - name: j3
```

However, when uncommenting `j4`, the same error occurs:

```console
tasks.2.name: conflicting values "j4" and "j3":
```

This is because of how the comprehension is written.

It's attempting to merge the values of `_stages[2][0]` and `_stages[2][1]` into `tasks[2]`; it is not creating a new element for each job at `_stages[2]`. Therefore, a conflict error occurs, as the names do not match.

Writing it like so works:

```cue
tasks: [for stage in _stages for job in stage.jobs {
        name: job.name
}]
```

```yaml
tasks:
  - name: j1
  - name: j2
  - name: j3
  - name: j4
```

And finally with the conditionals:

```cue
tasks: [for i, stage in _stages for job in stage.jobs {
        name: job.name
        if i > 0 {
            runAfter: _stages[i-1].jobs
        }
}]
```

```yaml
tasks:
  - name: j1
  - name: j2
    runAfter:
      - name: j1
  - name: j3
    runAfter:
      - name: j2
  - name: j4
    runAfter:
      - name: j2
```
