### DISCUSSION TITLE
Help with "unresolved disjunction"

### DISCUSSION THREAD

**Discussion by Otoru** [cue-lang/cue#2040] [Q&A]
With the following schema:
```
#Kind:  "Flag" | "Attribute"

#Flag: {
	name:            strings.MinRunes(1)
	description?:  string
	key:                strings.MinRunes(1)
        value:             strings.MinRunes(1)
}

#Attribute: {
	archived?:     (true | *false) & bool
	description?: string
	name:           strings.MinRunes(1)
	key:               strings.MinRunes(1)
}

kind:     #Kind
if kind == "Attribute" {
	specs: [#Attribute, ...#Attribute]
}

if kind == "Flag" {
	specs: [#Flag, ...#Flag]
}
```

When will I validate this yaml:
```
kind: Attribute
specs:
  - key: TEST
    name: testing
    archived: false
    description: Attribute used to test a provider
```

I have this error:
```
unresolved disjunction "Audience" | "Flag" | "Attribute" (type string):
    ./schema.cue:18:4
```

And I need the spec list to be dynamic according to the kind value. Can you help me?
