### DISCUSSION TITLE
How to remove null values?

### DISCUSSION THREAD

**Discussion by mario-steinhoff-gcx** [cue-lang/cue#2433] [Q&A]
Hello,

I use cue for kubernetes configuration and want to render helm charts via `helm template` and validate the resulting manifests against the cue-based kubernetes schema.

Rendering the template works and I can import manifests from helm stdout via `yaml.UnMarshalStream()`.

Some helm charts (argocd in this example) produce YAML with empty keys because they are using this pattern, where the field itself is not additionally guarded by an if block:

```plain
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  [...]
  annotations:
    {{- range $key, $value := .Values.server.metrics.serviceMonitor.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
```

Which renders to:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server
  labels:
    helm.sh/chart: argo-cd-5.14.1
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
  annotations:
spec:
  [...]
```

After I run it through yaml umarshalling and marshalling like this:

```cue
command: helm: {
  helm: exec.Run & {
    stdin:  helmCommand.out.stdin
    cmd:    helmCommand.out.command
    stdout: string
  }
  helmTemplateResult: {
    for obj in yaml.UnmarshalStream(helm.stdout) {
      kubernetes: "\(obj.kind)": "\(obj.metadata.name)": obj
    }
  }
  print: cli.Print & {
    text: yaml.Marshal(helm.helmTemplateResult)
  }
}
```

I get this result:

```yaml
kubernetes:
  ServiceMonitor:
    argocd-server:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: argocd-server
        labels:
          helm.sh/chart: argo-cd-5.14.1
          app.kubernetes.io/name: argocd-server
          app.kubernetes.io/instance: argocd
          app.kubernetes.io/component: server
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/part-of: argocd
        annotations: null
      spec:
        [...]
```

But the generated cue schema for annotations looks like this:

```cue
// Annotations is an unstructured key value map stored with a resource that may be
// set by external tools to store and retrieve arbitrary metadata. They are not
// queryable and should be preserved when modifying objects.
// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
// +optional
annotations?: {[string]: string} @go(Annotations,map[string]string) @protobuf(12,bytes,rep)
```

And of course null is not a struct with string fields so it doesnt validate in cue but its still accepted by the kubernetes API server.

In jsonnet there is `std.prune()` to remove null fields, is there a way to solve this with cue?
