### DISCUSSION TITLE
Validate YAML string, which itself is YAML

### DISCUSSION THREAD

**Discussion by hansbogert** [cue-lang/cue#2772] [Q&A] [answered]
It's probably asked before, but I think use-case is missing from the docs, AFAICT.

Is it possible to have a k8s yaml as the following:

```
...
spec:
  values: |
    annotations:
      key: "format, which, should, have, commas"
```

I'd like to verify `.spec.values.annotations.key`, however as you noticed, the `values` is a string, not an object.

Of course in the above the first question is, why is `values` a string in the first place? Unfortunately this seems to be common in the kubernetes/helm ecosystem. At least in my case, in the short-term, it's out of my control to go and convert this `values` to an object.

Can Cuelang help in this case and help validate that the string `key` has a comma separated text?
