### DISCUSSION TITLE
load input files dynamically

### DISCUSSION THREAD

**Discussion by fchastanet** [cue-lang/cue#3223] [Q&A] [answered]
Hello,

is possible to load input files dynamically from the first input file.
In other words, I would like to combine yaml files like it's done in the guide https://cuelang.org/docs/howto/combine-multiple-yaml-files-by-using-file-metadata/ but dynamically.

First input file would be:
```yaml
vars:
  REPOSITORY_URL: https://github.com/fchastanet/bash-tools-framework
includes:
  - path/fileToinclude1.yaml
  - path/fileToinclude2.yaml
```

path/fileToinclude1.yaml content:
```yaml
binFile:
  relativeRootDirBasedOnTargetDir: ..
  templateFile: binFile.gtpl
```

path/fileToinclude2.yaml content:
```yaml
vars:
  MAIN_FUNCTION_NAME: main
```

The resulting file would be:
````yaml
vars:
  REPOSITORY_URL: https://github.com/fchastanet/bash-tools-framework
  MAIN_FUNCTION_NAME: main
binFile:
  relativeRootDirBasedOnTargetDir: ..
  templateFile: binFile.gtpl
````

So in cue file, I could have something like
Writing this issue, I realized that I don't know how I could merge these files even by passing them via command line
this would probably not work
```yaml
# provide first input file 
input: _
mergeIncludes: {
  for _content in input.includes {
    _content
  }
}
```
