### DISCUSSION TITLE
Enforcing unique enum values in a CUE List Schema

### DISCUSSION THREAD

**Discussion by EdenCore** [cue-lang/cue#3456] [Q&A] [answered]
Hello,

Does someone know how to convert the following definition ?

```YAML
boot_device_order_list:
  description: >
      Indicates the order of device types in which VM
      should try to boot from. If boot device order is
      not provided the system will decide appropriate
      boot device order.
  items:
    type: string
    x-ntnx-enum:
      - CDROM
      - DISK
      - NETWORK
  type: array
  ```
  
  I have tried the following naive approach:
  
  ```CUE
  values: "CDROM" | "DISK" | "NETWORK"
#boot_device_order_list: [...values]
#boot_device_order_list & ["CDROM"]
//conflicting values ["CDROM"] and {values:("CDROM"|"DISK"|"NETWORK"),#boot_device_order_list:[...values],(#boot_device_order_list & ["CDROM"])} (mismatched types list and struct):
    -:1:1
    -:3:27
  ```
  
  Also please note that the list size must be 1=< and =<3 . Each enum value can only be used once.
