### DISCUSSION TITLE
Howto best describe OpenTelemetry based config structure

### DISCUSSION THREAD

**Discussion by cueckoo** [cue-lang/cue#580] [Q&A]
_Originally opened by @ekarlso in https://github.com/cuelang/cue/discussions/580_

Hi all, I'm trying to describe in CUE the structure for OpenTelemetry but I am a bit at of a question mark of how to do it.

Below you see a example of how the config can be, the top level structure is 
```
receivers:
  opencensus:
    cors_allowed_origins:
    - http://test.com
    # Origins can have wildcards with *, use * by itself to match any origin.
    - https://*.example.com
  prometheus: {}
  prometheus/1: {}
  
exporters:
  jaeger: {}
  zipkin: {}
  prometheus
  prometheus/1: {}

service:
  extensions: ["pprof", "zpages"]
  pipelines:
    traces:
     receivers: ["zipkin", "jaeger"]
     exporters: ["zipkin"]

  metrics:
    receivers: ["prometheus"]
    exporters: ["prometheus"]
  metrics/1:
    receivers: ["prometheus", "prometheus/1"]
    exporters: ["prometheus/1"]
```

So then I thought of defining a map of `{string: #ReceiverEnum}` kind of but then I can't enforce the receiver / exporter name etc that OTEL relies on since it doesnt define the type | component type based on a attribute inside the config but that falls short of validating the component like receiver | exporter name.

I've not done all of the exporters etc but the below is examples
```
#OTELPrometheusReceiver: {
      buffer_count?: string
      buffer_period?: string
      use_start_time_metrics?: string
      start_time_metrix_regex?: string
      scrape_configs: [...#ScrapeJob]
  }

  #OTELZipkinReceiver: {
  }

  #OTELJaegerReceiver: {
    protocols?: {
      grpc?: _
      thrift_http?: _
      thrift_binary?: _
      thrift_compact?: _
    }

    remote_sampling: {
      host_endpoint?: string
      strategy_file?: string
    }
  }

  #OTELExporter: _
  #OTELProcessor: _
  #OTELExtension: _
  #OTELReceivers: {
    { [string]: #OTELZipKinReceiver | #OTELPrometheusReceiver | #OTELJaegerReceiver }
  }
```
