### DISCUSSION TITLE
Checking for relations between elemets

### DISCUSSION THREAD

**Discussion by cueckoo** [cue-lang/cue#715] [Q&A] [answered]
_Originally opened by @ostcar in https://github.com/cuelang/cue/discussions/715_

I am a beginner of cue and would be pleased for some tips.

I am trying to validate an existing yaml-file. There are relation between elements in that file. In the following example, a node can have a `parent` and a list of `childs`. If a node has a parent, the node must be in the child list of its parent:

`data.yml`
```yaml
nodes:
- name: foo
  childs:
  - bar
  - baz

- name: bar
  parent: foo

- name: baz
  parent: foo
```

`schema.cue`
```cue
nodes: [...#Node]

#Node: {
	name: string
	childs?: [...string]
	parent?: string
}
```

How would you validate the relation?

I am using version `cue version v0.3.0-beta.3 linux/amd64`
