### ISSUE TITLE
Ho to handle conflicts in CUE

### ISSUE THREAD

**Issue by SephVelut** [cue-lang/cue#1208]
I don't think this use case is supported, so here goes.

For me, 99% of all issues I have with configuration management comes from conflicts between similar configs. Here is a simple example of a conflict.

Let's say I a fictitious program that reads configuration files and sets iptables firewall rules accordingly.
ConfigFile1 states that port 8000 should be OPEN.
ConfigFile2 states that port 8000 should be CLOSED.

That is an obvious conflict. What's worse, it could be idempotent, if the program reads the config files in the exact same order each time. First opening, then closing, every time. Then we never get to discover through inconsistent behavior that something fishy is going on. This accounts for nearly all of my configuration woes. 

Here is an example of another type of conflict.
ConfigFile1 states that id be INCREMENTED.
ConfigFile2 states that id be INCREMENTED.

Due to ConfigFile2 being a very sneaky file, somewhere deep in the directory structure, we never discover this conflict, and id gets incremented twice, when the configuration was only meant to do it once. Duplication of effort.

Another type of conflict can be redundancy. Different from duplication, but this one, at least, I think Cue already handles. 

Dealing with conflicts where a value is different for two keys of the same name is easy.
{key1: val1} conflicts with {key1: val2}

But what about when the logic is more complex? 
{key1: "open"} ???? {key1: "close"}
I would love to be able to define a schema that describes maybe a union or something to make the values exclusive to variants.
enum Value { OPEN, CLOSE }
{key1: Value::OPEN} conflicts with {key1: Value::CLOSE}

It would be really nice too, if when handling conflicts, you can annotate key/value pairs to inform on which conflicts are to be ignored. CSS does this with the "!" override. 
{key1: Value::OPEN} and {key1: Value::CLOSE ! } Exclamation overrides, so no conflict. Though, without unification, this then becomes dependent on the order the configs are read.

**Comment by IMBlues** [comment]
I have similar needs.

In the configuration definition, hope to provide configurations of different priorities.

### An immature idea
```yaml
global_labels: {
  some-common-key: "default-values-for-every-module"
}

local_labels: {
  # like css ?
  !some-common-key: "for-specific-one"
}

# local_labels has a higher priority and will directly override, won't conflict
pod_labels: global_labels & local_labels
```
