### ISSUE TITLE
cmd/cue: yaml import indents multiline string values incorrectly

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#122]
_Originally opened by @rogpeppe in https://github.com/cuelang/cue/issues/122_

Using `cue import` on the following YAML:
```
a:
  a:
    a:
      a:
        a: |
            This should be indented more.
      b: 1
    b: 1
  b: 1
```

results in the following cue. The multiline string should be indented at the same level as its parent element:

```
a: {
	a: {
		a: {
			a a: """
		This should be indented more.

		"""

			b: 1
		}
		b: 1
	}
	b: 1
}
```
