### ISSUE TITLE
How to verify the boolean field in yaml in cue?

### ISSUE THREAD

**Issue by silenceper** [cue-lang/cue#1255]
the deploy.yaml :
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
```

check.cue:
```
kind: "Deployment" | "Statefulset"
spec: {
    replicas: int
	template: {
		spec: {
			hostNetwork: bool & true
		}
	}
}
```

execute data verification:
```
 cue vet deploy.yaml check.cue
```

The result I hope to get is that the authentication fails, and I set hostNetwork to true
