### ISSUE TITLE
[question] validation list of elements

### ISSUE THREAD

**Issue by juev** [cue-lang/cue#1274]
Hello!

I trying to validate list like this:

```yaml
---
- id: FIRST_EL
  queries:
    - sql: "select 1 from database1"
      name: first_query
    - sql: "select 2 from database1"
      name: second_query
      intrval: 4
      tim: 5
- id: SECOND_EL
  queries:
    - sql: "select 3 from database2"
      name: first_query1
    - sql: "select 4 from database2"
      name: second_query1
```

I was try Schema like:
```plain
#query: {
	name: string
	sql: string
	interval?: *1 | int
        timeout?: *5 | int
}

#ids: {
    id: string
	queries: [...#query]
}

[...#ids]
```

and try validating my yaml:
```bash
 cue vet -c -E -s -v config.yaml rules.cue
```

Validating was successful. 

I was try to use only one element, like:
```plain
#query: {
	name: string
	sql: string
	interval?: *1 | int
        timeout?: *5 | int
}

#ids: {
    id: string
	queries: [...#query]
}

[#ids]
```

and only first item in config:
```yaml
---
- id: FIRST_EL
  queries:
    - sql: "select 1 from database1"
      name: first_query
    - sql: "select 2 from database1"
      name: second_query
      intrval: 4
      tim: 5
```

after this validating was failed:
```log
0.queries.1: field not allowed: intrval:
    ./config.yaml:3:2
    ./config.yaml:8:8
    ./rules.cue:1:1
    ./rules.cue:1:9
    ./rules.cue:10:15
    ./rules.cue:13:1
    ./rules.cue:13:2
```

What wrong with using list of items? Why validating of lists is not working?

Maybe I wring with my schema?

**Comment by slewiskelly** [comment]
There are a couple of typos in your example, which the error message is hinting at.

You have `tim` and `intrval` instead of `timeout` and `interval`. 

The following works:

```cue
// rules.cue
#query: {
        name:      string
        sql:       string
        interval?: *1 | int
        timeout?:  *5 | int
}

#ids: {
        id: string
        queries: [...#query]
}

[#ids]
```

```yaml
# config.yaml
- id: FIRST_EL
  queries:
    - sql: "select 1 from database1"
      name: first_query
    - sql: "select 2 from database1"
      name: second_query
      interval: 4
      timeout: 5
```

**Comment by verdverm** [comment]
@juev I believe the issue might have to do with embedding the list at the file level (`[...#ids]`). I suspect this reopens the #queries such that it is allowing additional fields. I'm not sure if this is a bug or working as intended.

If I add `#IDS: [...#ids]` to your schema, and then run the following, I get what looks to be your expected output.

```shell
$ cue vet -c -d '#IDS' dbl.yaml schema.cue 
0.queries.1: field not allowed: intrval:
    ./dbl.yaml:2:2
    ./dbl.yaml:8:8
    ./schema.cue:1:9
    ./schema.cue:10:15
    ./schema.cue:13:11

$ cue vet -c -d '#IDS' sng.yaml schema.cue 
0.queries.1: field not allowed: intrval:
    ./schema.cue:1:9
    ./schema.cue:10:15
    ./schema.cue:13:11
    ./sng.yaml:2:2
    ./sng.yaml:8:8
```

---

@slewiskelly I think the spelling errors are intentional and what is trying to be errored on.

**Comment by verdverm** [comment]
```cue
#A: {
  foo: string
}

#B: {
    bar: string
    a: #A
}

#C: {
    cow: string
    #B
}

[...#C]

[{
    x: string
    a: x: string
}]
```

This looks to be allowed, but when not embedded at the root, it does not work

https://cuelang.org/play/?id=sqZptl_LxL3#cue@export@cue

---
this one might be more demonstrative: https://cuelang.org/play/?id=z7ynQ1rIE23#cue@export@cue

**Comment by juev** [comment]
@slewiskelly my example contains several typo, cue vet should told me about these typos. And you example contains only one element. This work, but couple elements not.

@verdverm Tony, thank you! It's grait suggestion! 

```plain
#query: {
	name: string
	sql: string
	interval?: *1 | int
        timeout?: *5 | int
}

#ids: {
    id: string
	queries: [...#query]
}

#IDS: [...#ids]
```

and adding parameter `-d '#IDS'` work as expected!

Thank you!

**Comment by verdverm** [comment]
I'm not sure we should close this, there is ambiguity as to whether your original example should work. My intuition is that it should

**Comment by juev** [comment]
I checked my code with you solution. And its work.

**Comment by verdverm** [comment]
Yes, my solution works.

What I am saying is that I think your original code should probably work too.

**Comment by juev** [comment]
I think should too. But this issue just question. And i think for bug needed new issue?
If needed, I can open this issue.

**Comment by slewiskelly** [comment]
Apologies, I completely missed the point!

As a couple of additional data points, it seems like this is only an issue with open-ended lists, closed lists seem to work fine, as suggested by the example of using single element, but also a closed list of multiple elements:

```cue
// rules.cue
#query: {
        name:      string
        sql:       string
        interval?: *1 | int
        timeout?:  *5 | int
}

#ids: {
        id: string
        queries: [...#query]
}

[#ids, #ids]
```

```yaml
# config.yaml
---
- id: FIRST_EL
  queries:
    - sql: "select 1 from database1"
      name: first_query
    - sql: "select 2 from database1"
      name: second_query
- id: SECOND_EL
  queries:
    - sql: "select 3 from database2"
      name: first_query1
    - sql: "select 4 from database2"
      name: second_query1
      intrval: 4
      tim: 5
```

```console
$ cue vet config.yaml rules.cue
1.queries.1: field not allowed: intrval:
    ./config.yaml:2:2
    ./config.yaml:14:8
    ./rules.cue:1:1
    ./rules.cue:1:9
    ./rules.cue:10:15
    ./rules.cue:13:1
    ./rules.cue:13:8
```

This also causes `cue vet` to (incorrectly) succeed:

```cue
// rules.cue
#query: {
        name:      string
        sql:       string
        interval?: *1 | int
        timeout?:  *5 | int
}

#ids: {
        id: string
        queries: [...#query]
}

[#ids, #ids, ...#ids]
```

However, removing `[...#ids]` from the `rules.cue` and then using the same expression via `-d` validates correctly:

```console
$ cue vet config.yaml rules.cue -d '[...#ids]'
1.queries.1: field not allowed: intrval:
    --schema:1:5
    ./config.yaml:2:2
    ./config.yaml:14:8
    ./rules.cue:1:9
    ./rules.cue:10:15
```
