### ISSUE TITLE
reference root

### ISSUE THREAD

**Issue by ghost** [cue-lang/cue#1402]
I have the following cue file:

```cue
metadata:
  labels:
    label1: val1
spec:
  metadata: metadata.labels
```

If I try to export this I receive an error that labels is not accessible.
From what I understand from the docs is that the nearest reference will be used for resolving. In this case the metadata under spec.

How can I explicitly reference to the root? I would expect something like $.metadata.labels or something like this, but I have found nothing in the docs.

Thank you for your assistance

**Comment by eonpatapon** [comment]
You can use an alias:

```
M=metadata:
  labels:
    label1: val1
spec:
  metadata: M.labels
  ```
