### ISSUE TITLE
CUE does not import "example:" fields from openapi spec

### ISSUE THREAD

**Issue by obernil** [cue-lang/cue#1501]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
`cue import openapi3sample.yaml`

(see [openapi3sample.yaml](https://gist.github.com/obernil/25a648cd77ea2ddf0427283325a52d2b) for full gist)

-- openapi3sample.yaml --
```
...
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 18446744073709551614
        name:
          type: string
        tag:
          type: string
...
```

### What did you expect to see?

-- openapi3sample.cue --

```
// Swagger Petstore

info: {
	version: *"1.0.0" | string
	title:   *"Swagger Petstore" | string
	license: name: "MIT"
}

#Pet: null | bool | number | string | [...] | {
	//example id: 18446744073709551614
	id:   int
	name: string
	tag?: string
	...
}
#Pets: [...#Pet]
#Error: null | bool | number | string | [...] | {
	code:    int
	message: string
	...
}

```

### What did you see instead?

-- openapi3sample.cue --

```
// Swagger Petstore

info: {
	version: *"1.0.0" | string
	title:   *"Swagger Petstore" | string
	license: name: "MIT"
}

#Pet: null | bool | number | string | [...] | {
	id:   int
	name: string
	tag?: string
	...
}
#Pets: [...#Pet]
#Error: null | bool | number | string | [...] | {
	code:    int
	message: string
	...
}
```
