### ISSUE TITLE
cmd/cue: fmt is less flexible than gofmt

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#1731]
**Is your feature request related to a problem? Please describe.**

Coming from Go, we have `go fmt` and `gofmt` - the former works on packages, and the latter works on files or stdin and has more features, such as the `-d` flag to see the difference that formatting would make without writing it to disk.

CUE learns from `go fmt` with `cue fmt`, but it does not have a `cuefmt`. So the ability to format entire directories (ignoring package patterns), stdin, or to show diffs, is currently not present.

**Describe the solution you'd like**

I think it would be reasonable to teach `cue fmt` these features, for example via flags like `-d` or `-diff`, and `-f` or `-file` to work on files rather than packages.

**Describe alternatives you've considered**

We could also introduce a `cuefmt`, but it feels somewhat unnecessary, and in Go people get very confused between the two tools.

I would even argue that formatting with files and directories is better than with packages - formatting packages can make it harder when one wants to format multiple modules at once (e.g. monorepos). But that would be a form of breaking change.

**Additional context**

> One fmt to rule them all - @Lyoness

**Comment by mvdan** [comment]
One other flag that would be nice is `cue fmt -l`, to print the filenames that were modified, borrowing from `gofmt -l`.

**Comment by seh** [comment]
See #363 for previous coverage.

**Comment by seh** [comment]
Here are two compensatory steps from a GitHub Actions workflow job that I wrote:
```yaml
# At present, "cue fmt" only mutates, and has no reporting mode.
# See:
# - https://github.com/cuelang/cue/issues/363
# - https://github.com/cuelang/cue/pull/247
- name: Format CUE files
  run: |
    cue fmt ./...
- name: Ensure no CUE files were reformatted
  run: |
    test -z "$(git status --porcelain)" || (git status --short; git diff; false)
```
I don't like it one bit.
