### ISSUE TITLE
encoding/cue: add support to encode/decode cue code to/from a string

### ISSUE THREAD

**Issue by Somefive** [cue-lang/cue#1852]
**Is your feature request related to a problem? Please describe.**

In KubeVela, we use pure CUE file to write and organize render logics but the code is embedded as YAML object while deployed into Kubernetes cluster.

For example, the following CUE file will be converted into the following YAML object.

```cue

scaler: {
	type: "trait"
	annotations: {}
	labels: {}
	description: "Manually scale K8s pod for your workload which follows the pod spec in path 'spec.template'."
	attributes: {
		podDisruptive: false
		appliesToWorkloads: ["deployments.apps", "statefulsets.apps"]
	}
}
template: {
	parameter: {
		// +usage=Specify the number of workload
		replicas: *1 | int
	}
	// +patchStrategy=retainKeys
	patch: spec: replicas: parameter.replicas
}
```

```yaml
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: Manually scale K8s pod for your workload which follows the pod spec in path 'spec.template'.
  name: scaler
  namespace: {{ include "systemDefinitionNamespace" . }}
spec:
  appliesToWorkloads:
    - deployments.apps
    - statefulsets.apps
  podDisruptive: false
  schematic:
    cue:
      template: |
        parameter: {
        	// +usage=Specify the number of workload
        	replicas: *1 | int
        }
        // +patchStrategy=retainKeys
        patch: spec: replicas: parameter.replicas
```

Reference:
- https://github.com/kubevela/kubevela/blob/master/vela-templates/definitions/internal/trait/scaler.cue
- https://github.com/kubevela/kubevela/blob/master/charts/vela-core/templates/defwithtemplate/scaler.yaml

Currently, we use `vela def render` command to do the conversion. The conversion logic includes:
- Find out CUE in `template` field and convert into string and fill it into `spec.schematic.cue.template`.
- Parse the rest struct into metadata or other fields.

Therefore, although the YAML object can be rendered from the CUE file, the CUE file itself is not actually cue native, as the fields in the `template` field are actually isolated from other fields.

**Describe the solution you'd like**

If we have some internal function like `cue.Marshal` from `encoding/cue`, just like `encoding/json` and `json.Marshal`, we can make the CUE rendering process more elegant. For example, with this function we can write,

```cue
// scaler.cue
import (
  "encoding/cue"
)

parameter: {
        name: "scaler"
	type: "trait"
	annotations: {}
	labels: {}
	description: "Manually scale K8s pod for your workload which follows the pod spec in path 'spec.template'."
	attributes: {
		podDisruptive: false
		appliesToWorkloads: ["deployments.apps", "statefulsets.apps"]
	}
        template: {
	        parameter: {
		        // +usage=Specify the number of workload
		        replicas: *1 | int
	        }
	        // +patchStrategy=retainKeys
	        patch: spec: replicas: parameter.replicas
        }
}

output: {
        apiVersion: "core.oam.dev/v1beta1"
        kind: strings.ToTitle(parameter.type) + "Definition"
        metadata: {
                name: parameter.name
                annotations: {
                        parameter.annotations
                        "definition.oam.dev/description": parameter.description
                }
                labels: parameter.labels
        }
        spec: {
                parameter.attributes
                schematic: cue: template: cue.Marshal(parameter.template)
        }
}
```
And then we could use `cue eval scaler.cue -e output -d yaml | kubectl apply -f -n vela-system -` to get the rendered YAML object and apply it into Kubernetes cluster directly.

**Describe alternatives you've considered**

**Additional context**
