### ISSUE TITLE
Tutorial request:  Transform CRD input to kustomization output

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#221]
_Originally opened by @wstrange in https://github.com/cuelang/cue/issues/221_

As a user, I want to be able to POST a CRD to a CUE program, and get back transformed kustomization output expanded using template values from the CRD.

For example:

crd.yaml:
```
kind: myCRD
version: 1.0
spec:
  app:
    instances: 3
    memory: 10Gi
    cpu:  5000m
  domain: example.com
  namespace: prod'`
```

Run:
`curl -X POST http://blah/cue --data  @crd.yaml`

Response is transformed output:

```
kind: kustomization
namespace: prod
resources:
- github.com:/blah/blah?ref=v1.0.1
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: myapp
  spec:
    replicas: 3
    template:
      spec:
        containers:
        - name: nginx
          image: nginx:latest
        resources:
        requests:
          cpu: 5000m
          memory: 10Gi
```
