### ISSUE TITLE
cmd/cue: export with defaults gives different values depending on the encoding

### ISSUE THREAD

**Issue by littlecatherine** [cue-lang/cue#2575]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version

cue version v0.6.0

go version go1.20.6
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

```
cue export --out yaml

-- test.cue --
#HelmValues: images?: {
		component?: {
			tag?: null | string | *null
		}
}

#HelmValues: {
    images: {
        _tag: string
        component: tag: string | *"\(_tag)" @tag(build)
    }
}

myapp: values: #HelmValues & {
	images: _tag: "2.4.3"
}

```

### What did you expect to see?

```
myapp:
  values:
    images:
      component:
        tag: 2.4.3
```

### What did you see instead?
```
myapp:
  values:
    images:
      component:
        tag: null
```
The result is correct when I run "cue export" or "cue export --out json", only "cue export --out yaml" gives the incorrect result.
