### ISSUE TITLE
Cue does not interpret accented letters as it should in .yaml

### ISSUE THREAD

**Issue by fedy97** [cue-lang/cue#2651]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version 0.6.0

</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

create a `test.yaml` file like this

```yaml
test: line1èèèèèèèèèèèèèèèè
test2: line2
test3: line3
```
or like this 
```yaml
test: "line1èèèèèèèèèèèèèèèè"
test2: "line2"
test3: "line3"
```

and a `policy.cue` script like this

`test3: number`

then, run `cue eval test.yaml policy.cue`

### What did you expect to see?

```
./test.yaml:3:9
./policy.cue:1:8
```

### What did you see instead?

```
./test.yaml:2:6
./policy.cue:1:8
```

As you can see, cue returns the wrong line number in the yaml file. It seems like the `è` is deleting some character before it, in fact if I use this `test.yaml`
```yaml
test: line1èèèè
test2: line2
test3: line3
```
and run `cue eval` with the `policy.cue` above, it returns  `./my-ci.yaml:3:5`. In this case the row is ok, but the column `5` is incorrect
