### ISSUE TITLE
cue/cmd: `import crd` for importing Kubernetes CustomResourceDefinitions

### ISSUE THREAD

**Issue by justenstall** [cue-lang/cue#2691]
## Is your feature request related to a problem? Please describe.

CUE cannot import [Kubernetes CustomResourceDefinitions (CRDs)](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions). Importing CRDs into CUE would be a huge value add for Kubernetes users.

## Describe the solution you'd like

I would like a `cue import crd` command that is able to import a YAML or JSON encoded CustomResourceDefinition to CUE.

### `cue import openapi`

Since CRDs use a variation of OpenAPIv3 to define their schema, `cue import openapi` can be used to import the schema with some extra help from a query tool like yq. Here is an example script to extract a valid OpenAPI definition from the CRD with yq and then import it as CUE:

```sh
CRD="<file>.yaml"

yq '{"openapi": "3.0.0"} *
	{"info": {"title": .spec.group}} *
	{"info": {"version": .spec.versions[0].name}} *
	{"components": { "schemas": { .spec.names.kind: .spec.versions[0].schema.openAPIV3Schema}}}' \
	"$CRD_FILE" > crd-openapi.yaml 

cue import openapi crd-openapi.yaml
```

This is not a viable solution because of Kubernetes' OpenAPIv3 extensions explained in the _Additional Context_ section below.

### `cue get go`

Many CRDs are created with a code generation tool such as [`controller-gen`](https://book.kubebuilder.io/reference/controller-gen) (from the [kubebuilder SDK](https://book.kubebuilder.io/)), which generates the CRD from annotated Go code. I have used `cue get go` to import the CRD from the Go types, but it is not a 100% match for the `controller-gen`-created schema. Adding direct support for CRD --> CUE is ideal.

> See also: #2679 

### OpenAPIv3 vs Structural Schema

Kubernetes calls its flavor of OpenAPIv3 "structural schema", which is defined as follows:

> A structural schema is an [OpenAPI v3.0 validation schema](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation) which:
>
> 1. specifies a non-empty type (via type in OpenAPI) for the root, for each specified field of an object node (via properties or additionalProperties in OpenAPI) and for each item in an array node (via items in OpenAPI), with the exception of:
>    - a node with x-kubernetes-int-or-string: true
>    - a node with x-kubernetes-preserve-unknown-fields: true
> 2. for each field in an object and each item in an array which is specified within any of allOf, anyOf, oneOf or not, the schema also specifies the field/item outside of those logical junctors (compare example 1 and 2).
> 3. does not set description, type, default, additionalProperties, nullable within an allOf, anyOf, oneOf or not, with the exception of the two pattern for x-kubernetes-int-or-string: true (see below).
> 4. if metadata is specified, then only restrictions on metadata.name and metadata.generateName are allowed.

Source: [Specifying a structural schema](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema)

### CEL Validation

As seen in the snippet above, Kubernetes extends the OpenAPIv3 syntax with fields prefixed by `x-kubernetes-`. The most challenging to incorporate will be the newer [`x-kubernetes-validations` field](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules), used to define validations rules with the [Common Expression Language (CEL)](https://github.com/google/cel-spec). Translating CEL to CUE will be a big lift, but it is being cemented as the desired way for k8s developers to define validation rules in CRDs, [k8s admission controller webhooks](https://github.com/kubernetes/cel-admission-webhook), and eventually even the native Kubernetes APIs. CEL validation will be incompatible with CUE in some cases, because it allows validating an updated Kubernetes object by comparing it to its existing values. Ideally, validation rules that have no CUE equivalent can be preserved so the CRD can round-trip CRD --> CUE --> CRD without losing information.

References:
- [Kubernetes Docs: Common Expression Language in Kubernetes](https://kubernetes.io/docs/reference/using-api/cel/)
- [Kubernetes Docs: CustomResourceDefinition Validation rules](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules)
- [YouTube: The Path to Self Contained CRDs - Cici Huang, Google](https://youtu.be/KIL1BAq3J2g?si=9kYs24kYy4TEjBSB)

### Possible existing implementation?

The file [encoding/openapi/crd.go](https://github.com/cue-lang/cue/blob/7a4ea8668a03d0cb2458ee264e5f582a2d5107e5/encoding/openapi/crd.go) contains a seemingly unused implementation of CRD decoding. If anyone is familiar with this code and knows what state it is in, I would appreciate the help as a new contributor.

**Comment by myitcv** [comment]
Thanks for raising this @justenstall 

This caused me to think about https://twitter.com/stefanprodan/status/1710632837362147563 

On that basis I'll copy in @stefanprodan and @sdboyer

**Comment by stefanprodan** [comment]
Some of the features described here are currently implemented in [timoni mod vendor crd](https://timoni.sh/cmd/timoni_mod_vendor_crd/). We currently can generate CUE schemas from CRD manifests made with controller-gen and kubebuilder markers, which cover most CNCF projects. We handle `x-kubernetes-preserve-unknown-fields` which was quite challenging, the cue openapi package makes everything opened by default, instead only fields with this prop must be so, Sam found a way to deal with using kin-openapi. For CRDs  that have `anyOf` and `oneOf` (luckily these are not supported by controller-gen so not many CRDs have them), the schema generated by cue is invalid (tracked in [#2686](https://github.com/cue-lang/cue/issues/2686)). Next we'll have to deal with `x-kubernetes-int-or-string`.

As for CEL, I agree that is a major undertake but I suspect most CRDs will switch to CEL in 2024. Kubernetes Gateway API already uses CEL, and we're also considering using CEL for FluxCD, guess many more project will follow. Given this, without a CEL to CUE translator, I think the value prop of using CUE for Kubernetes objects validation will be less attractive. To overcome this, I'm inclined into running CEL inside Timoni after CUE generates the final values, in the same way the Kubernetes API does, but it would be ideal for CUE to provide a CEL translator, at least for the expressions that are compatible.

**Comment by justenstall** [comment]
Linking the following in case they could be of use:
- #2528: describes a CRD/CEL-related blocker for the Istio team
- <https://github.com/istio/tools/pull/2674>: Istio PR replacing CUE, mentions a fork of CUE to explore CEL support

**Comment by justenstall** [comment]
I put together a rough demo for this functionality using the [Timoni CRD importer](https://github.com/stefanprodan/timoni/blob/45fc31689ba2fcd576553ddf0ad33c6e44a01909/internal/engine/importer.go) as a starting point. By switching from `kin-openapi` to Kubernetes' [internal representation](https://pkg.go.dev/k8s.io/apiextensions-apiserver@v0.28.3/pkg/apis/apiextensions/v1#CustomResourceDefinition) of a CRD it should hopefully be easier to work with their API extensions. The only additional functionality in the demo is that all Kubernetes extensions to OpenAPI (`x-kubernetes-*` fields) are preserved in the resulting CUE as attributes.

I think this sort of implementation would be the best way to make CRD imports lossless and would allow the CRD importing functionality to be made available independent of a CEL to CUE translator, which could theoretically be added at a later date.

https://github.com/justenstall/cue/blob/get-crd/encoding/crd/decode.go

**Example**

For [`extensions.istio.io/v1alpha1.WasmPlugin`](https://github.com/istio/istio/blob/0d5f530188dfe571bf0d8f515618ba99a0dc3e6c/manifests/charts/base/crds/crd-all.gen.yaml#L150), the field `spec.url` uses `x-kubernetes-validations`:

```yaml
url:
  description: URL of a Wasm module or OCI container.
  minLength: 1
  type: string
  x-kubernetes-validations:
  - message: url must have schema one of [http, https, file, oci]
    rule: 'isURL(self) ? (url(self).getScheme() in ['''', ''http'',
      ''https'', ''oci'', ''file'']) : (isURL(''http://'' + self) &&
      url(''http://'' +self).getScheme() in ['''', ''http'', ''https'',
      ''oci'', ''file''])'
```

<details>

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  ...
spec:
  group: extensions.istio.io
  names:
    kind: WasmPlugin
    ...
  versions:
  - name: v1alpha1
    ...
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              ...
              url:
                description: URL of a Wasm module or OCI container.
                minLength: 1
                type: string
                x-kubernetes-validations:
                - message: url must have schema one of [http, https, file, oci]
                  rule: 'isURL(self) ? (url(self).getScheme() in ['''', ''http'',
                    ''https'', ''oci'', ''file'']) : (isURL(''http://'' + self) &&
                    url(''http://'' +self).getScheme() in ['''', ''http'', ''https'',
                    ''oci'', ''file''])'
                ...
```

</details>

This is the resulting CUE in `cue.mod/gen/extensions.istio.io/wasmplugin/v1alpha1/types_gen.cue`:

```cue
url: strings.MinRunes(1) @crd(validations="""
                              [{"rule":"isURL(self) ? (url(self).getScheme() in ['', 'http', 'https', 'oci', 'file']) : (isURL('http://' + self) \u0026\u0026 url('http://' +self).getScheme() in ['', 'http', 'https', 'oci', 'file'])","message":"url must have schema one of [http, https, file, oci]"}]
                              """)
```

<details>

```cue
package v1alpha1

import (
	"strings"
	"list"
)

#WasmPlugin: {
  // Extend the functionality provided by the Istio proxy through
  // WebAssembly filters. See more details at:
  // https://istio.io/docs/reference/config/proxy_extensions/wasm-plugin.html
  spec!:      #WasmPluginSpec
  apiVersion: "extensions.istio.io/v1alpha1"
  kind:       "WasmPlugin"
  metadata!: {
    ...
  }
}

// Extend the functionality provided by the Istio proxy through
// WebAssembly filters. See more details at:
// https://istio.io/docs/reference/config/proxy_extensions/wasm-plugin.html
#WasmPluginSpec: {
  ...
  // URL of a Wasm module or OCI container.
  url: strings.MinRunes(1) @crd(validations="""
                                [{"rule":"isURL(self) ? (url(self).getScheme() in ['', 'http', 'https', 'oci', 'file']) : (isURL('http://' + self) \u0026\u0026 url('http://' +self).getScheme() in ['', 'http', 'https', 'oci', 'file'])","message":"url must have schema one of [http, https, file, oci]"}]
                                """)
  ...
}
```

</details>
