### ISSUE TITLE
fields generated out of order

### ISSUE THREAD

**Issue by Awadabang** [cue-lang/cue#3174]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.2

go version go1.21.5
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

Cue File:
```
_environments: [
    "0",
    "1"
]

stages: [
	"lint",
	"diff",
	"apply"
]

".k8s-workloads-image": {
 	image: name: "registry.gitlab.com/gitlab-com/gl-infra/ci-images/k8s-workloads:1.2.0"
}

for k, _ in _environments {
	"\(k):dryrun": {
	  extends: ".k8s-workloads-image"
	  resource_group: "\(k)"
	  script: """
	make gen
	"""
	  stage: "dryrun"
	}
}
```

<pre>
$ cue export test.cue --out yaml
</pre>

### What did you expect to see?

```
stages:
  - lint
  - diff
  - apply
.k8s-workloads-image:
  image:
    name: registry.gitlab.com/gitlab-com/gl-infra/ci-images/k8s-workloads:1.2.0
0:dryrun:
  extends: .k8s-workloads-image
  resource_group: "0"
  script: make gen
  stage: dryrun
1:dryrun:
  extends: .k8s-workloads-image
  resource_group: "1"
  script: make gen
  stage: dryrun
```

### What did you see instead?

```
stages:
  - lint
  - diff
  - apply
0:dryrun:
  extends: .k8s-workloads-image
  resource_group: "0"
  script: make gen
  stage: dryrun
.k8s-workloads-image:
  image:
    name: registry.gitlab.com/gitlab-com/gl-infra/ci-images/k8s-workloads:1.2.0
1:dryrun:
  extends: .k8s-workloads-image
  resource_group: "1"
  script: make gen
  stage: dryrun
```
