### ISSUE TITLE
Cue reorders fields when the key overlaps with the builtins

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#349]
_Originally opened by @verdverm in https://github.com/cuelang/cue/issues/349_

### What version of CUE are you using (`cue version`)?

> master @ 904f561e349f96f336b51430f0ccb9817a361b87 (April 16)

### Does this issue reproduce with the latest release?

> Yes

### What did you do?

```yaml
ex: {
  "aaa": "aaa",
  "list": "list",
  "zzz": "zzz",
  "AAA": "AAA",
  "html": "html",
  "HTML": "html",
  "ZZZ": "ZZZ",
  "Html": "html",
}
```

`cue eval`

### What did you expect to see?

The original order

### What did you see instead?

keys which overlap with builtins are sorted at the front of the struct. This happens for both definitions and values.

```yaml
ex: {
    html: "html"
    list: "list"
    aaa:  "aaa"
    zzz:  "zzz"
    AAA:  "AAA"
    HTML: "html"
    ZZZ:  "ZZZ"
    Html: "html"
}
```
