### ISSUE TITLE
Unify function is generating incorrect output when merging values from trait with default parameters in Kubevela

### ISSUE THREAD

**Issue by shivin** [cue-lang/cue#3623]
### What version of CUE are you using (`cue version`)?
<pre>
$ cue version
0.9.2

</pre>

### Does this issue reproduce with the latest stable release?
Didn't try

### Testing environment ?
1. Kubernetes cluster 
2. Vela cli installed
3. Kubevela installed and running on the Kubernetes cluster 

### What did you do?
1. Copy the below contents into comp.cue.

```
mincomp: {
	alias: ""
	annotations: {}
	attributes: workload: definition: {
		apiVersion: "apps/v1"
		kind:       "Deployment"
	}
	description: ""
	labels: {}
	type: "component"
}

template: {
	output: {
            kind:       "Deployment"
	    volumes: [{
		name:  "myEmpty"
	}]
    }
	outputs: {}
}

```
5. Copy the below contents into trait.cue.

```
"min-trait": {
	type: "trait"
}

template: {
	patch: 
		// +patchKey=name
		volumes: [{
			name: parameter.volumeName
		}]

	parameter: {
		// +usage=name of host mount volume (default datadog)
		volumeName: *"my-default-vol" | string
	}
}

```

6. Copy the below contents into app.yaml.

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: hello
      type: mincomp
      traits:
        - type: min-trait
```

7. Apply the component: `vela def apply comp.cue` 
8. Apply the trait: `vela def apply trait.cue`
9. Dry run the application: `vela dry-run -f app.yaml`

### What did you expect to see?
After running the dry-run command we expect to see the below output:

```
---
# Application(website) -- Component(hello) 
---

kind: Deployment
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: hello
    app.oam.dev/name: website
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: mincomp
  name: hello
  namespace: default
volumes:
- name: myEmpty
- name: my-default-vol

---
```

### What did you see instead?

After running the dry-run command we are seeing below output instead: 
 
```
---
# Application(website) -- Component(hello) 
---

kind: Deployment
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: hello
    app.oam.dev/name: website
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: mincomp
  name: hello
  namespace: default
volumes:
- name: myEmpty

---
```

### Issue Description ?
Basically volume defined in trait is missing after the merge.
After debugging the kubevela codebase we observed that the kubevela is calling cue's Unify function to do the merging of volumes and it is not generating the expected output causing the above issue. 

You can read more about the issue [here](https://github.com/kubevela/kubevela/issues/6510)
