### ISSUE TITLE
Strange behavior when generating openapi v3 from protobuf definition with field-trailing comments

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#586]
_Originally opened by @harveyxia in https://github.com/cuelang/cue/issues/586_

### What version of CUE are you using (`cue version`)?

v0.2.2

### Does this issue reproduce with the latest release?

Yes, v0.2.2 is the latest release

### What did you do?

When generating openapi v3 schema from a protobuf definition, resulting `oneOf` fields are not permitted to be omitted.

For example, the following protobuf definition,

```protobuf
message Bar {

    oneof Foo {
        string a = 1;
        // hello world

        string b = 2;
        // hello world
    }
}
```

generates the following openapi v3 schema:

```yaml
properties:
  spec:
    oneOf:
    - not:
        anyOf:
        - required:
          - a
        - {}
        - required:
          - b
        - {}
    - required:
      - a
    - not:
        anyOf:
        - {}
        - required:
          - a
        - required:
          - b
        - {}
    - required:
      - b
    - not:
        anyOf:
        - {}
        - required:
          - a
        - {}
        - required:
          - b
    properties:
      a:
        type: string
      b:
        type: string
    type: object
  status:
    type: object
type: object
```

Whereas the same protobuf definition without the trailing comments:

```protobuf
message Bar {

    oneof Foo {
        string a = 1;
        string b = 2;
    }
}
```

produces the following openapi v3 schema:

```yaml
properties:
  spec:
    description: A WasmDeployment deploys one or more WASM Envoy Filters to selected Sidecars and Gateways in a Mesh.
    oneOf:
    - not:
        anyOf:
        - required:
          - a
        - required:
          - b
    - required:
      - a
    - required:
      - b
    properties:
      a:
        type: string
      b:
        type: string
    type: object
  status:
    type: object
type: object
```

### What did you expect to see?

I would expect the presence of trailing comments to not affect how the protobuf definition is parsed / interpreted.
