### ISSUE TITLE
Vet doesn't output data files location when erroring

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#681]
_Originally opened by @marcosnils in https://github.com/cuelang/cue/issues/681_

### What version of CUE are you using (`cue version`)?

<pre>
cue version 0.3.0-beta.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Latest beta release

### What did you do?

Followed the example on https://cuelang.org/docs/tutorials/tour/intro/validation/

### What did you expect to see?

`cue vet` output in the example URL listed on the link above

### What did you see instead?

```
# cue vet data.yaml schema_ext.cue 
languages.1.name: invalid value "dutch" (out of bound =~"^\\p{Lu}"):
    ./schema_ext.cue:3:8
```

As you can see it's missing the error reference in the data file.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/681#issuecomment-769914797_

Hey there @marcosnils!

Confirmed in a6169255 via:

```
exec cue vet schema.cue data.yaml

-- data.yaml --
languages:
  - tag: en
    name: English
  - tag: nl
    name: dutch
  - tag: no
    name: Norwegian
-- schema.cue --
#Language: {
	tag:  string
	name: =~"^\\p{Lu}" // Must start with an uppercase letter.
}
languages: [...#Language]
```

cc @mpvl
